----------------------------------------------------------------------
Ran 3 tests in 73.137s

OK
----------------------------------------------------------------------
Ran 1 test in 0.012s

OK
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
----------------------------------------------------------------------
Ran 3 tests in 0.134s

OK
----------------------------------------------------------------------
Ran 1 test in 0.250s

OK
----------------------------------------------------------------------
Ran 1 test in 0.418s

OK
----------------------------------------------------------------------
Ran 1 test in 3.037s

OK
----------------------------------------------------------------------
Ran 1 test in 0.462s

OK
----------------------------------------------------------------------
Ran 1 test in 0.271s

OK
----------------------------------------------------------------------
Ran 2 tests in 0.296s

OK
----------------------------------------------------------------------
Ran 1 test in 14.316s

OK
----------------------------------------------------------------------
Ran 1 test in 2.293s

OK
----------------------------------------------------------------------
Ran 1 test in 0.014s

OK
======================================================================
ERROR: test_mail (test_mail.TestMail)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\xavierdupre\__home_\GitHub\botadi\_unittests\ut_mokadi\test_mail.py", line 46, in test_mail
    raise ValueError("user or pwd is not specified.")
ValueError: user or pwd is not specified.

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (errors=1)
